package main.chapter11_Exception_and_Localization._1_Understanding_Exceptions._2_Calling_Methods_That_Throw_Exceptions;

public class Exception3 {
    public static void main(String[] args) {

    }

//    public void bad() {
//        try {
//            eatCarrot();
//        } catch (NoMoreCarrotsException e) { // DOES NOT COMPILE
//            System.out.print("sad rabbit");
//        }
//    }

    private void eatCarrot() {} // не бросает исключение
}
